#!/bin/bash

if [ "$#" != 4 ] 
then
	echo "Usage: ./ftest.native infile source sink outfile"
	exit
fi

./make
./ftest.native $1 $2 $3 $4
dot -Tpng "output/$4" > "output/$4.png"
display "output/$4.png"

