#!/bin/bash
clear
./make

if [ "$#" == 2 ] 
then
	infile="application/$1"
	outfile="output/$2"
	./ftest.native $infile $outfile
elif [ "$#" == 4 ]
then
	infile="graph/$1"
	source=$2
	sink=$3
	outfile="output/$4"
	./ftest.native $infile $source $sink $outfile
else
	echo "Usage: ./launch infile source sink outfile : to call FordFulkerson on a graph"
	echo "Usage: ./launch infile outfile : to test the application"
	exit
fi

dot -Tpng $outfile > "$outfile.png"
display "$outfile.png"

echo ""
